"""
LiuAlgoTrader Integration — Multi-process ML-ready framework adapter.
Bridges our strategies to work within LiuAlgoTrader's event-driven architecture.

NOTE: Install separately: pip install liualgotrader
      Requires PostgreSQL for production use.
"""

from typing import Optional
from datetime import datetime

import pandas as pd

from src.utils.logger import get_logger

logger = get_logger(__name__)


class LiuAlgoTraderBridge:
    """
    Adapter to run our custom strategies through LiuAlgoTrader's framework.

    LiuAlgoTrader provides:
    - Multi-process execution (separate processes for data, strategy, execution)
    - Built-in Alpaca integration
    - PostgreSQL-backed trade history
    - Real-time scanners
    - Built-in ML model serving

    This bridge lets you use LiuAlgoTrader's infrastructure while keeping
    our strategy logic.
    """

    def __init__(self, config_path: str = "liualgo_config.toml"):
        self.config_path = config_path
        self._liu_available = self._check_available()

    def _check_available(self) -> bool:
        try:
            import liualgotrader
            return True
        except ImportError:
            return False

    def create_config(
        self,
        symbols: list[str],
        alpaca_api_key: str,
        alpaca_secret: str,
        paper: bool = True,
        db_url: str = "postgresql://localhost/liu_trading",
    ) -> str:
        """
        Generate a LiuAlgoTrader TOML configuration file.

        Args:
            symbols: Trading symbols
            alpaca_api_key: Alpaca API key
            alpaca_secret: Alpaca secret key
            paper: Paper or live trading
            db_url: PostgreSQL connection string

        Returns:
            Path to generated config file
        """
        base_url = "https://paper-api.alpaca.markets" if paper else "https://api.alpaca.markets"

        config = f"""
# LiuAlgoTrader Configuration
# Generated by algo-trader bridge at {datetime.now().isoformat()}

[alpaca]
api_key = "{alpaca_api_key}"
api_secret = "{alpaca_secret}"
base_url = "{base_url}"

[database]
dsn = "{db_url}"

[trading]
symbols = {symbols}
market_open_offset_minutes = 5
market_close_offset_minutes = 5

[risk]
max_portfolio_pct = 0.80
max_single_position_pct = 0.15

[scanner]
# Momentum scanner for stock picking
[scanner.momentum]
min_volume = 500000
min_price = 5.0
max_price = 500.0
min_change_pct = 2.0
"""
        with open(self.config_path, 'w') as f:
            f.write(config)

        logger.info("liu.config_generated", path=self.config_path)
        return self.config_path

    def create_strategy_file(self, strategy_name: str = "momentum") -> str:
        """
        Generate a LiuAlgoTrader-compatible strategy file that wraps our logic.
        """
        code = '''"""
LiuAlgoTrader Strategy — wraps algo-trader's momentum strategy.
Place this file in your LiuAlgoTrader strategies directory.
"""

from liualgotrader.common.types import TimeScale
from liualgotrader.strategies.base import Strategy

import pandas as pd
import numpy as np


class MomentumLiu(Strategy):
    """Momentum strategy adapted for LiuAlgoTrader."""

    name = "momentum_liu"

    def __init__(self, batch_id: str, ref_run_id: int = None, **kwargs):
        super().__init__(
            name=self.name,
            batch_id=batch_id,
            ref_run_id=ref_run_id,
            **kwargs,
        )
        self.fast_ema = kwargs.get("fast_ema", 12)
        self.slow_ema = kwargs.get("slow_ema", 26)

    async def buy_callback(self, symbol: str, price: float, qty: int, **kwargs):
        """Called when a buy order fills."""
        pass

    async def sell_callback(self, symbol: str, price: float, qty: int, **kwargs):
        """Called when a sell order fills."""
        pass

    async def create(self):
        """Initialize strategy state."""
        await super().create()

    async def run(
        self,
        symbol: str,
        shortable: bool,
        position: int,
        now: pd.Timestamp,
        portfolio_value: float,
        trading_api,
        debug: bool = False,
        backtesting: bool = False,
    ) -> tuple:
        """
        Main strategy logic — called on each bar.
        Returns: (buy, sell) booleans
        """
        # Get recent bars
        bars = trading_api.get_bars(symbol, TimeScale.Minute, 50)
        if bars is None or len(bars) < self.slow_ema + 5:
            return False, False

        close = pd.Series([b.close for b in bars])
        fast = close.ewm(span=self.fast_ema, adjust=False).mean()
        slow = close.ewm(span=self.slow_ema, adjust=False).mean()

        # EMA crossover
        if position == 0:
            # No position: look for entry
            if fast.iloc[-1] > slow.iloc[-1] and fast.iloc[-2] <= slow.iloc[-2]:
                return True, False  # Buy signal
        else:
            # Has position: look for exit
            if fast.iloc[-1] < slow.iloc[-1] and fast.iloc[-2] >= slow.iloc[-2]:
                return False, True  # Sell signal

        return False, False

    async def is_sell_time(self, now: pd.Timestamp) -> bool:
        """Check if it's time to consider selling."""
        return True

    async def is_buy_time(self, now: pd.Timestamp) -> bool:
        """Check if it's time to consider buying."""
        return True
'''

        output_path = f"strategies/{strategy_name}_liu.py"
        import os
        os.makedirs("strategies", exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(code)

        logger.info("liu.strategy_generated", path=output_path)
        return output_path

    def run_scanner(self):
        """Run LiuAlgoTrader's scanner to find trading opportunities."""
        if not self._liu_available:
            logger.error("liu.not_installed", msg="Install: pip install liualgotrader")
            return []

        try:
            from liualgotrader.scanners.momentum import Momentum
            # Would integrate with their scanner framework
            logger.info("liu.scanner_run")
        except ImportError:
            logger.warning("liu.scanner_unavailable")
        return []
